### ISSUE TITLE
Video Steganography

### ISSUE THREAD

**Issue by deepak-kiran** [Spidy-PS/Steganography-Tools#5]
Well.. you have passed variable frame_ ( i.e "a")  in decode function for decoding which is taken from Encode video function.
Generally we perform Encode and decode in different devices where there won't be value frame_ while decoding in a new device.
Which throws a error.

**Comment by Priyansh-15** [comment]
Hi @deepak-kiran ,
**Yes in the decode section of the video steganography I have passed the frame in the decode function .**
```
def decode_vid_data(frame_):
    cap = cv2.VideoCapture('stego_video.mp4')
    max_frame=0;
    while(cap.isOpened()):
        ret, frame = cap.read()
        if ret == False:
            break
        max_frame+=1
    print("Total number of Frame in selected Video :",max_frame)
    print("Enter the secret frame number from where you want to extract data")
    n=int(input())
    vidcap = cv2.VideoCapture('stego_video.mp4')
    frame_number = 0
    while(vidcap.isOpened()):
        frame_number += 1
        ret, frame = vidcap.read()
        if ret == False:
            break
        if frame_number == n:
            extract(frame_)
            return
```

**It is necessary to pass that frame in decode function to just show that the encode function works well and do it task in encoding secret message in a particular frame.**

_Ideally  In the decode function, we just need to pass the stego_video to get the secret code as done in other steganographic techniques like Image, Text and Audio,_ **_but the problem lies that after encoding the message and the RC4 encryption, the stego video format is not supported in python3 as of now which gives individual frame,_** _that's why it can't be decoded normally like other decode function ._

**The stego_video is correct and holds our secret message and is similar to the cover video, it's just python3 don't support that video format to execute and extract each frame from it .**

_Hence in order to just show that the encode function works well and the message is encoded and encrypted into the frame of video, I passed the frame in decode._ 


> **_Moreover, If you make a cpp code for encode and decode for Video Steganography, You won't need to pass frame in that, It's just that cpp supports the format of stego_video to extract and work on frame, Till now python3 didn't support it._**


**Hope you understand it .
Feel Free to ask any other queries .**

_**Thanks**_ 
@Priyansh-15

**Comment by deepak-kiran** [comment]
If RC4 is removed does it work without passing the frame?

**Comment by Priyansh-15** [comment]
No @deepak-kiran , **It's not because of that we are doing any particular encryption on text, I have tried many encryption algorithms on data to be encoded in any type of steganographic technique . It doesn't affect the encoding algorithm.** 

_**This also make it easy to understand that for the encoded algorithm , the type of input doesn't really matters, whether it's a plain text or encrypted text because we are doing encryption before encoding so according to me it won't be the case .**_

Hope you understand it 
Thanks 
@Priyansh-15

**Comment by deepak-kiran** [comment]
Thank you for the clarification.
